on:
  push:
    branches:
      - main

env:
  PACKAGE_NAME: "django-deepl"
  OWNER: "iTz-i-Soldier"
  UPLOAD_TO_PYPI: "false" 

jobs:
  setup_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build source and wheel distribution
        run: |
          python setup.py sdist bdist_wheel

      - name: Upload artifacts
        uses: actions/upload-artifact@v3  
        with:
          name: dist
          path: dist/

  pypi_publish:
    name: Upload release to PyPI
    needs: [setup_and_build]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Check if upload is enabled
        run: |
          if [[ "${{ env.UPLOAD_TO_PYPI }}" == "true" ]]; then
            echo "Upload to PyPI is enabled. Proceeding with the upload."
          else
            echo "Upload to PyPI is disabled. Skipping the upload."
            exit 0  # Salta il passo se l'upload è disabilitato
          
      - name: Publish distribution to PyPI
        if: env.UPLOAD_TO_PYPI == 'true'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

  github_release:
    name: Create GitHub Release
    needs: [setup_and_build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v3  
        with:
          name: dist
          path: dist/

      - name: Create GitHub Release
        id: create_release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ github.sha }} dist/* --title "Release ${{ github.sha }}" --generate-notes
