name: release

on:
  push:
    branches:
      - main 

env:
  PACKAGE_NAME: "django-deepl"
  OWNER: "iTz-i-Soldier"

jobs:
  details:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Get current version from setup.py
        id: version
        run: |
          VERSION=$(python -c "from setuptools import setup; print(setup().get('version'))")
          echo "Current version: $VERSION"
          echo "version=$VERSION" >> "$GITHUB_ENV"

  setup_and_build:
    needs: details
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build source and wheel distribution
        run: |
          python setup.py sdist bdist_wheel

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/

  pypi_publish:
    name: Upload release to PyPI
    needs: [setup_and_build, details]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Check if version has changed
        id: check_version
        run: |
          VERSION_IN_REPO=$(python -c "from setuptools import setup; print(setup().get('version'))")
          echo "Current version in setup.py: $VERSION_IN_REPO"

          # Check if the version in setup.py is different from the version in the last tag
          LAST_TAG=$(git describe --tags --abbrev=0)
          echo "Last tag: $LAST_TAG"
          
          if [[ "$VERSION_IN_REPO" == "$LAST_TAG" ]]; then
            echo "No version change detected. Skipping PyPI upload."
            echo "upload_to_pypi=false" >> $GITHUB_ENV
          else
            echo "Version change detected. Proceeding with PyPI upload."
            echo "upload_to_pypi=true" >> $GITHUB_ENV

      - name: Publish distribution to PyPI
        if: env.upload_to_pypi == 'true'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

  github_release:
    name: Create GitHub Release
    needs: [setup_and_build, details]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist/

      - name: Create GitHub Release
        id: create_release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ github.sha }} dist/* --title "Release ${{ github.sha }}" --generate-notes
